services:
  api:
    container_name: game_reviews_api
    build:
      context: ../
      dockerfile: Dockerfile
      args:
        - PORT=$PORT
        - POSTGRES_USER=$POSTGRES_USER
        - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
        - POSTGRES_HOST=db
        - JWT_SECRET=$JWT_SECRET
    ports:
      - ${PORT}:${PORT}
    networks:
      - game-reviews
    restart: always
    depends_on:
      db:
        condition: service_healthy
  db:
    container_name: game_reviews_postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /data/postgres
      POSTGRES_DB: game_reviews
    volumes:
      - db:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - game-reviews
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  game-reviews:
    driver: bridge

volumes:
  db:
